### ISSUE TITLE
[Missing] 'AceConsole-3.0'-Lib is missing in the lib

### ISSUE THREAD

**Issue by lorem-ipsum-dolor-sit** [NumyAddon/LazyCurve#4]
https://github.com/Numynum/LazyCurve/blob/e847a8ce76dce90c510f855bc46d7860a78be418/LazyCurve.lua#L17
https://github.com/Numynum/LazyCurve/blob/e847a8ce76dce90c510f855bc46d7860a78be418/libs/embeds.xml#L1-L7
You use a reference of `AceConsole-3.0` but not include it in the `/libs/embeds.xml.`

> Message: Interface\AddOns\LazyCurve\LazyCurve.lua:16: Usage: EmbedLibrary(addon, libname, silent, offset): 'libname' - Cannot find a library instance of "AceConsole-3.0".
Time: Tue Jan 19 15:31:24 2021
Count: 1

Works for most people cause other add-ons deliver an instance of `AceConsole-3.0`

**Comment by Numynum** [comment]
Good catch, should be fixed next release :)
